### ISSUE TITLE
压缩包解压需要密码

### ISSUE THREAD

**Issue by libhgis** [YuHuanTin/IDM_Cracker#4]
请问您是如何解压的呢？或者说是从哪里得到的解压密码？谢谢！

**Comment by YuHuanTin** [comment]
压缩包里就有写

**Comment by libhgis** [comment]
大佬，压缩包里是有密码1234，但是我用的bandizip好像必须输完密码才能看到里面的文件:)

**Comment by YuHuanTin** [comment]
> 大佬，压缩包里是有密码1234，但是我用的bandizip好像必须输完密码才能看到里面的文件:)

压缩包里有个文件叫 password=1234的....
